version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ../images:/app/images 
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped 
